services:
  - type: web
    name: currency-converter
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: heroku-php-apache2 public/
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://currency-converter.onrender.com
      - key: SI2t1o/+hTywXUiKfbWjw5zsuqDZigpyT6wKliq2FJc=
        sync: false  # You'll set this manually in Render dashboard

        